# Set default shell
set -g default-shell $SHELL

# check colors with
# curl -s https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh | bash
set -g default-terminal 'tmux-256color'
set -sa terminal-overrides ',xterm*:RGB'
set -as terminal-features ',*:hyperlinks'

# mouse support
set -g mouse on

# Set prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind Space send-prefix

# Vim style pane selection
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# 0 is too far from ` ;)
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Automatically set window title
setw -g automatic-rename on
set -g set-titles on
set -g automatic-rename-format '#{b:pane_current_path}'

# Rename and lock (disables auto-rename and shell title override for this window)
bind , {
  set-window-option automatic-rename off
  set-window-option allow-rename off
  command-prompt -p "Window name:" "rename-window '%%'"
}
# Restore auto-rename for current window
bind N {
  set-window-option automatic-rename on
  set-window-option allow-rename on
}

# Lets you know when any activity has happened
setw -g monitor-activity on
set -g visual-activity on

# Open panes in currect directory
bind '"' split-window -v -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'

set -g history-limit 100000

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persiste tmux session after restart
set -g @plugin 'tmux-plugins/tmux-continuum' # save session every 15min
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_text ' #{window_name} '
set -g @catppuccin_window_current_text '#[bold,italics] #{window_name} '
set -g @catppuccin_host_text ' #h'

run-shell 'bash ~/.config/tmux/run_tpm.sh'

set -g status-left-length 100
set -g status-right-length 100
set -g status-left '#{E:@catppuccin_status_host}'
set -ag status-left '#{E:@catppuccin_status_session}'
set -g status-right '#{E:@catppuccin_status_application}'
set -agF status-right '#{E:@catppuccin_status_cpu}'
set -ag status-right '#{E:@catppuccin_status_date_time}'

run-shell '~/.config/tmux/plugins/tmux-cpu/cpu.tmux'

# vim style
setw -g mode-keys vi

# select and copy vim style
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

